# Numpy Array Operations:  Axes and Broadcasting 

There is an excellent introduction to `numpy` multi-dimensional arrays on the [scipy](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html) website.  In this note, we cover two concepts in a little more detail:
* Using the `axis` feature 
* Python broadcasting

We will need both of these for performing many of the numerical operations for the ML class.

As usual, we begin by loading the `numpy` package.

In [2]:
import numpy as np

## Axis Parameter

Many operations in the `numpy` package can take an optional `axis` parameter to specify which dimensions the operation is to be applied.  This is extremely useful for multi-dimensional data.  To illustrate the `axis` parameter, consider a matrix the `(3,2)` array `X` defined as:

In [3]:
X = np.arange(6).reshape(3,2)#生成6个元素矩阵并重新shape成3行2列
print(X)

[[0 1]
 [2 3]
 [4 5]]


An operation like `np.mean` or `np.sum` takes the mean or sum of *all* elements in the array. 

In [4]:
print(np.mean(X))
print(np.sum(X))

2.5
15


To take only the `sum` along each column, we can use the `axis` parameter.

In [5]:
print(np.mean(X,axis=0))#axis = 0表示竖直方向，axis = 1表示水平方向，对水平方向取平均数，矩阵由3*2变为1*2
print(np.sum(X,axis=0))#水平方向上求和，矩阵由3*2变为1*2 axis处在哪个维度就收缩那个维度(以...为轴 )

[2. 3.]
[6 9]


Since `X` has shape `(3,2)`, the output `np.sum(X,axis=0)` is of shape `(2,)`.  Similarly, we can take the `sum` along each row:

In [6]:
print(np.sum(X,axis=1))#水平方向求和(对每列进行求和)

[1 5 9]


You can apply this to higher-order arrays:

In [7]:
X = np.arange(24).reshape(2,3,4)  # shape = (2,3,4)这才叫三维矩阵
Y0 = np.sum(X,axis=0)             # shape = (3,4)
Y1 = np.sum(X,axis=1)             # shape = (2,4)
Y2 = np.sum(X,axis=2)             # shape = (2,3)
print('X = ')
print(X)
print('Y0 = ')
print(Y0)
print('Y1 = ')
print(Y1)
print('Y2 = ')
print(Y2)

X = 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Y0 = 
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
Y1 = 
[[12 15 18 21]
 [48 51 54 57]]
Y2 = 
[[ 6 22 38]
 [54 70 86]]


## Broadcasting

**Broadcasting** is a powerful tool in Python for performing operations on matrices that we will use throughout the ML class.  A good tutorial on broadcasting can be found on the [scipy broadcasting page](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html).  Here we provide some examples.   

### Example 1:  Mean Removal

Suppose that `X` is a data matrix of shape `(n,p)`.  That is, there are `n` data points and `p` features per point.  Often, we have to remove the mean from each feature.  That is, we want to compute the mean for each feature and then remove the mean from each column.  We could do this with a for-loop as:
   
    Xm = np.zeros(p)      # Mean for each feature
    X1_demean = np.zeros((n,p))  # Transformed features with the means removed
    for j in range(p):
       Xm[j] = np.mean(X[:,j])
       for i in range(n):
           X_demean[i,j] = X[i,j] - Xm[j]
           
The code below does this without a for loop using the `axis` parameter and broadcasting.

In [8]:
# Generate some random data
n = 10
p = 4
X = np.random.rand(n,p)
print(X,X.shape)
print('X[:,:] = ','\n',X[:,:],X[:,:].shape)#1
print('X[:,] = ','\n',X[:,],X[:,].shape)#2
print('X[None,:] = ','\n',X[None,:],X[None,:].shape)#3
print('X[:,None] = ','\n',X[:,None],X[:,None].shape)#4
print('X[None,None] = ','\n',X[None,None],X[None,None].shape)#5
print('X[None,None,:] = ','\n',X[None,None,:],X[None,None,:].shape)#6
# 1 = 2 
# 5 = 6
# 3,4互为转置
# None相当于增加一个维度,强行把数组转化为矩阵，因为数组不能参与numpy.array的操作
# Compute the mean per column using the axis command
Xm = np.mean(X,axis=0)  # This is a p-dim matrix axis = 0 对每列取平均值
# Subtract the mean

[[0.71794052 0.14903807 0.23011439 0.85473954]
 [0.83433253 0.035321   0.99401511 0.88126509]
 [0.21744893 0.96639831 0.81512184 0.61057898]
 [0.70213556 0.4389362  0.60194498 0.33208814]
 [0.43518321 0.77261223 0.40333032 0.72486398]
 [0.56799405 0.64766041 0.31149332 0.85009345]
 [0.96643453 0.25772365 0.71628463 0.14552988]
 [0.42434768 0.24231289 0.78031021 0.35239952]
 [0.77764588 0.70706987 0.1362349  0.30649203]
 [0.25324017 0.47702661 0.04657431 0.73218014]] (10, 4)
X[:,:] =  
 [[0.71794052 0.14903807 0.23011439 0.85473954]
 [0.83433253 0.035321   0.99401511 0.88126509]
 [0.21744893 0.96639831 0.81512184 0.61057898]
 [0.70213556 0.4389362  0.60194498 0.33208814]
 [0.43518321 0.77261223 0.40333032 0.72486398]
 [0.56799405 0.64766041 0.31149332 0.85009345]
 [0.96643453 0.25772365 0.71628463 0.14552988]
 [0.42434768 0.24231289 0.78031021 0.35239952]
 [0.77764588 0.70706987 0.1362349  0.30649203]
 [0.25324017 0.47702661 0.04657431 0.73218014]] (10, 4)
X[:,] =  
 [[0.71794052 0.1490

In [9]:
print(Xm) #自动退化为list的向量,不能进行形如[:.]的操作，需要用reshape或者None进行修正
print(Xm[None,:],'\n',Xm[:,None]) #行矩阵和列矩阵，哪边长度为1哪边为None
print(Xm[0:],'\n',Xm[:0]) #按位操作向量
print(Xm.shape,Xm[None,:].shape,Xm[:,None].shape,Xm[0:].shape,Xm[:0].shape)

[0.5896703  0.46940992 0.5035424  0.57902308]
[[0.5896703  0.46940992 0.5035424  0.57902308]] 
 [[0.5896703 ]
 [0.46940992]
 [0.5035424 ]
 [0.57902308]]
[0.5896703  0.46940992 0.5035424  0.57902308] 
 []
(4,) (1, 4) (4, 1) (4,) (0,)


The command `Xm = np.mean(X,axis=0)` computes the mean of each column which is a `p` dimensional array.  Then, `Xm[None,:]` converts this to a `(1,p)` shape array.  Using Python broadcasting, we can then subtract the `Xm[None,:]` from `X`.

### Example 2:  Standardizing variables

A variant of the above example is to *standardize* the features, where we compute the transform variables,

    Z[i,j] = (X[i,j] - Xm[j])/ Xstd[j]
    
where `Xstd[j]` is the standard deviation per feature.  This can be done as follows:

In [10]:
Xstd = np.std(X,axis=0)
Z1 = (X-Xm[None,:])/Xstd[None,:]
Z2 = (X-Xm)/Xstd
Z3 = (X - np.mean(X,axis = 0))/np.std(X,axis = 0)
Z4 = (X - np.mean(X,axis = 0)[None,:])/np.std(X,axis = 0)[None,:]
print(Z1,'\n',Z2,'\n',Z3,'\n',Z4)

[[ 0.53743025 -1.12178243 -0.89439139  1.07233489]
 [ 1.02509289 -1.51996291  1.60435122  1.17549982]
 [-1.55954394  1.74020544  1.01918586  0.12272932]
 [ 0.4712102  -0.10670377  0.32187786 -0.96039584]
 [-0.64727452  1.06166325 -0.32779679  0.56721419]
 [-0.09081982  0.62414429 -0.62819843  1.05426502]
 [ 1.5785777  -0.74121975  0.69588635 -1.68597069]
 [-0.69267355 -0.79518053  0.90531597 -0.88139946]
 [ 0.78758554  0.83216659 -1.20147406 -1.05994593]
 [-1.40958476  0.02666982 -1.49475659  0.59566869]] 
 [[ 0.53743025 -1.12178243 -0.89439139  1.07233489]
 [ 1.02509289 -1.51996291  1.60435122  1.17549982]
 [-1.55954394  1.74020544  1.01918586  0.12272932]
 [ 0.4712102  -0.10670377  0.32187786 -0.96039584]
 [-0.64727452  1.06166325 -0.32779679  0.56721419]
 [-0.09081982  0.62414429 -0.62819843  1.05426502]
 [ 1.5785777  -0.74121975  0.69588635 -1.68597069]
 [-0.69267355 -0.79518053  0.90531597 -0.88139946]
 [ 0.78758554  0.83216659 -1.20147406 -1.05994593]
 [-1.40958476  0.02666982 -1

### Example 3:  Distances

Here is a more complicated example.  Suppose we have a data matrix `X` of shape `(nx,p)` and a second set of points, `Y` of shape `(ny,p)`. For each `i` and `j`, we want to compute the distances, 

     d[i,j] = np.sum((X[i,:] - Y[j,:])**2)
     
This represents the distances between the vectors `X[i,:]` and `Y[j,:]`.  This sort of computation is used for clustering and nearest neighbors.  We can do this without a for loop as follows

In [11]:
# Some random data
nx = 3
ny = 3
p = 2
X = np.array([[1,1,1]])
Y = np.array([[0,0,0]])

# Computing the distances in two lines.  No for loop!
DXY = X[:,None,:]-Y[None,:,:]
print(DXY,(DXY**2))#None相当于取投影
d = np.sum(DXY**2,axis=2)
print(d)

[[[1 1 1]]] [[[1 1 1]]]
[[3]]


How does this work? First, we use `None` keyword to reshape the matrices `X` and `Y` to compatible sizes

     X[:,None,:]    # Shape nx,  1, p
     Y[None,:,:]    # Shape 1,  ny, p
     
The two matrices can be subtracted so that

     DXY[i,j,k]  = X[i,k] - Y[j,k]
     
Then, `d[i,j] = sum_k (X[i,k] - Y[j,k])**2`, which is the norm squared of the vector differences.

### Example 4:  Outer product

The *outer product* of vectors `x` and `y` is the matrix `Z[i,j] = x[i]y[j]`.  This can be performed in one line as follows

In [13]:
# Some random data
nx = 3
ny = 3
x = np.random.rand(nx)
y = np.random.rand(ny).T
print(x[None,:].shape,y[None,:].shape)
# Compute the outer product in one line
Z1 = x[:,None]*y[None,:]
Z2 = np.dot(x[None,:],y[:,None]) #果然...
print('x = ',x,'\n','y = ',y,'\n',Z1,'\n','Z2 = ',Z2)

(1, 3) (1, 3)
x =  [0.59638746 0.16993324 0.10540418] 
 y =  [0.43105743 0.91176662 0.20503577] 
 [[0.25707724 0.54376618 0.12228076]
 [0.07325099 0.15493946 0.03484239]
 [0.04543525 0.09610401 0.02161163]] 
 Z2 =  [[0.43362833]]


Here:

     x[:,None] # Has shape (nx,  1)
     y[None,:] # Has shape ( 1, ny)
     
So, with python broadcasting:

     Z = x[:,None]*y[None,:] # has shape (nx,  ny)


**Exercise 1:**  Given a matrix `X`, compute the matrix `Y`, where the rows of `X` are normaized to one.  That is:

     Y[i,j] = X[i,j] / sum_j X[i,j]   

In [98]:
X = np.random.rand(4,3)
Y = X/np.sum(X,axis = 1)[:,None]
print(Y)

[[0.46821687 0.11696287 0.41482026]
 [0.50239663 0.04181354 0.45578983]
 [0.15637667 0.39167146 0.45195187]
 [0.34288259 0.56841625 0.08870116]]


**Exercise 2:** Diagonal multiplication.  Given a matrix `X` and a vector `d`, compute `Y = diag(d)*X`.

In [15]:
X = np.random.rand(5,3)
d = np.random.rand(5)
# Y = ...